GET http://localhost:3000/players/


###

GET http://localhost:3000/players/1/

###

POST http://localhost:3000/players/
Content-Type: application/json

{
    "playerName": "Rajesh",
    "jerseyNumber": 22,
    "role": "All-rounder"
}

###

PUT http://localhost:3000/players/16/
Content-Type: application/json

{
    "playerName": "Ranjith",
    "jerseyNumber": 45,
    "role": "Batter"
}

###

DELETE http://localhost:3000/players/12/